### ISSUE TITLE
Build and Deploy frequency

### ISSUE THREAD

**Issue by nishanth-kd** [ColoredCow/employee-portal#14]
Figure out a suitable build and deploy frequency for shipping code from developer's box to review, test and release on production.

**Comment by rathorevaibhav** [comment]
Build and deploy frequency:

1. Code review to be conducted at 11 am every day.
2. All review feedbacks are taken care within the day and then marked for testing.
3. All testing feedbacks are taken care within the day. Meanwhile, other code changes are also checked-in in their corresponding branches.
4. On the next day, the reviewed and accepted code is released to Production at 11 am.
5. Other code changes from the previous day are marked for code review.

Code changes should be targeted on a daily-release basis. This way, there'll be fewer chances of having a higher feedback and will ensure daily builds.

**Comment by nishanth-kd** [comment]
Looks good, lets move this to a wiki. and hook Travis ? when should we target this ? @rathorevaibhav

**Comment by rathorevaibhav** [comment]
Yes, KD. I'm in the middle of integrating Travis. Once done, I can target the wiki. 👍

**Comment by rathorevaibhav** [comment]
Added to the wiki. This is complete. Closing.
