### ISSUE TITLE
Finalize  the book categories. 

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/employee-portal#140]
We need to finalize the categories for all the books we have in our library.

**Comment by pankaj-ag** [comment]
@abhi1203 @PrateekNarang can you give your suggestions for categories.

**Comment by rathorevaibhav** [comment]
@pankaj-ag I believe this is complete. Please confirm (and close).

**Comment by pankaj-ag** [comment]
I was waiting for Prateek to test, but I think we close this one and open a new issue if something came up later.
