### ISSUE TITLE
Show the number of copies of a book

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/employee-portal#273]
##### Requirements
1. Add a new column `number_of_copies` in the database table `library_books`
1. This count will appear on the book card of that specific book
1. The `super-admin` and `book_manager` can click on this number to update the count
1. When a new book is added, an input field will ask the user to enter the number of copies available in the library

**Comment by rathorevaibhav** [comment]
@pankaj-ag I believe you meant `show the number of copies of a book`. Is that correct?

**Comment by abhishek-pokhriyal** [comment]
@pankaj-ag I've updated description. Please let me know if I missed something.

**Comment by abhishek-pokhriyal** [comment]
This issue is partially completed and the remaining work is being tracked in #629. Closing.
