### ISSUE TITLE
Move "reason for eligibility" to application meta form-data

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/employee-portal#337]
Currently, the field `reason_for_eligibility` is a column in `hr_application` table. We need to move this field to `application_meta` just like other `form_data` fields

**Comment by Satendra-SR** [comment]
> @rathorevaibhav  **and I have discussed on this issue and what I understood is:**
* I have to remove `reason_for_eligibiliy` from the **table** `hr_application`.
* The field `reason_for_eligibility` should be moved inside the `hr_application_meta` **table** as a `key-value` pair.

So **according to my understanding**, I **don't** have to create a new column inside the `hr_application_meta`. The data related to `reason_for_eligibility` will comes as a form data as a key-value pair in json form and we have to extract reason_for_eligibility from the json data.

**Comment by rathorevaibhav** [comment]
@Satendra-SR thanks for putting the summary. Just so that everyone's clear on this:

### Current internship request:
```js
"email" : "intern@example.com",
"form_data" : {
    "Why do you want to intern with us?" : "Lorem ipsum dolor sit amet",
    "What do you hope to achieve in this internship?" : "Lorem ipsum dolor sit amet",
}
```
This `form_data` is saved as json in the `application_meta` table.

### Current job request:
```js
"email" : "intern@example.com",
"reason_for_eligibility" : "Lorem ipsum dolor sit amet",
```

### New job request:
Reason for eligibility for jobs are currently being stored in `application` table and should moved to `application_meta` table:
```js
"email" : "job@example.com",
"form_data" : {
    "Reason for eligibility" : "Lorem ipsum dolor sit amet",
}
```
