### ISSUE TITLE
Search in the applicant listing

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/employee-portal#376]
We need a search field to look for an application by applicant name. For now, if we're viewing job applications, the search should happen only for the job applications. Same will be the case for the internship applications.

**Comment by Satendra-SR** [comment]
> @rathorevaibhav  **and I have discussed on this issue and what I understood is:**
* I need to add some changes to it for an enhanced search bar.
* Search bar should be enhanced and well aligned.
* Application count should be there, means we should have number of applications in each status type and should be shown with each status bar.
* Searched key should be there until we clear search history.
