### ISSUE TITLE
Option to trigger custom emails to the applicants at any time

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/employee-portal#378]
Currently, the application allows emails for specific actions. There's no way we can resend, in case there is an error, or send a custom email if we want. We need an option to send a custom email.

**Comment by abhishek-pokhriyal** [comment]
@rathorevaibhav explained this :

There is a card for each round (Resume screening, telephonic interview, etc). The card-footer contains three items:
1. A drop-down for selecting the next action
2. A Reject button for rejecting the application
3. A Send Mail button for sending a mail

Currently, the footer will disappear as soon as a mail is sent to the applicant in any round. 

This works fine but in case the application is rejected and a mail is sent, we would still like to see the drop down for taking further actions.

**Comment by abhishek-pokhriyal** [comment]
@rathorevaibhav where is the data related to this custom mail (sender, mail subject, mail message, etc.) going to be saved in the database?
