### ISSUE TITLE
New entity: college

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/employee-portal#414]
Colleges need to be tracked down.

- [x] College ID
- [x] College name
- [x] Address
- [x] TPOs (name and email: can be multiple TPOs)

**Comment by Satendra-SR** [comment]
Me And @bohraji  discussed the above issue and decide that I will do it in 2 phase
1. In first Phase, I did the  following
```
added new model as College and its migration as
php artisan make:model College -m
-new columns to the table
*college_id
*college-name
*address
```
2. In second phase I will do 
`Director (name and email) ?
 TPOs (name and email: can be multiple TPOs)`
@rathorevaibhav  @nishanth-kd  please let me know how I should append these information to the above.
should I create a new table for TPO, and what should I do with Director?

**Comment by Satendra-SR** [comment]
@rathorevaibhav 
can you please tell me what should I do with TPO and Director?
#414

**Comment by rathorevaibhav** [comment]
@Satendra-SR Let's hold the director for now. We can just use TPO emails. Now, TPO emails may or may not be multiple. We can use the implemented followed in client's emails to store TPO emails.
