### ISSUE TITLE
Add book manager role in the system. 

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/employee-portal#441]
Currently, we have 5 user roles in the system. 
1.	super-admin
2.	admin
3.	employee
4.	hr-manager
5.	accountant

We need a seeder to add a new role (Book Manager) in the system. Also, We need to map that role with all the permissions we defined for books module.

**Comment by abhishek-pokhriyal** [comment]
@pankaj-ag could you please explain a little bit about this issue.

**Comment by pankaj-ag** [comment]
@abhishek-pokhriyal I have updated the description. Let me know if you have any query on that.

**Comment by rathorevaibhav** [comment]
This is complete. Closing.
