### ISSUE TITLE
Invoice fields that are related to "paid" status should be required when status is paid

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/employee-portal#459]
The following fields should be required if invoice status is "paid".

- [x] Paid on
- [x] Received amount
- [x] Payment type
- [x] If payment type is cheque, check status and cheque date should be required

**Comment by Satendra-SR** [comment]
when I go through the issue, I saw that the paid information is visible if we select unpaid status.
When we create an invoice from **/finance/invoices/create** the paid section opens only when the status is paid. We can see below

**when the `status` is `unpaid`**
![unpaid2](https://user-images.githubusercontent.com/39792899/42432310-8cef1efe-8367-11e8-8985-e910045e77d4.png)

**when `status` is `paid`**
![unpaid3](https://user-images.githubusercontent.com/39792899/42432315-919d6816-8367-11e8-9918-e820644da82c.png)

Similarly, if we create an invoice from **/projects/2/edit**, the paid information is visible if the `unpaid` `status` is selected.
![unpaid1](https://user-images.githubusercontent.com/39792899/42432248-3c3ffe2e-8367-11e8-992a-702de0e9cf8e.png)

#459
@rathorevaibhav 
My query is, should we hide paid section until the paid section will not be selected?

**Comment by rathorevaibhav** [comment]
@Satendra-SR To your query, yes. The fields in the payment details section should be hidden until the status is "unpaid". When the status changes to "paid", the fields should show up.

Furthermore, this issue mentions that the fields in the  payment details should be required if the status is "paid". The form should not gets submitted if form validation fails and should report validation errors. This needs to be implemented at `invoice/create` and `invoice/edit` screens and also in the `create invoice modal` in the project stage screen.

Let me know if this resolves your query.

**Comment by Satendra-SR** [comment]
@rathorevaibhav
Thank you for the reply.  actually, I'm clear about my issue, but I saw something inappropriate, so I decided you should know that( if not already known).

**Comment by rathorevaibhav** [comment]
Thanks. That show/hide thing was meant to be fixed in other PR but got missed. Glad you noticed.

The show/hide thing is already implemented in the `invoice create` screen. You can reuse the code from there to put it in the project stage create invoice model.

**Comment by Satendra-SR** [comment]
@rathorevaibhav 
I just got to know that this is already an issue and assigned to @mohitgusain .
thank you.

**Comment by rathorevaibhav** [comment]
Complete. Further enhancements will be taken care in #611
