### ISSUE TITLE
Status modal doesn't disappear by clicking on x button.  

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/employee-portal#463]
When we enable the book suggestion notification the status modal doesn't disappear without page reload. 

![image](https://user-images.githubusercontent.com/10670690/41469200-017925a4-70ca-11e8-87cf-4d5d9254ba90.png)

**Comment by rathorevaibhav** [comment]
@pankaj-ag very weird it's not working. Can you put more details and pages where this is not working?

**Comment by pankaj-ag** [comment]
@rathorevaibhav currently this is the only page I know having this issue.

**Comment by rathorevaibhav** [comment]
This is complete. Closing.
