### ISSUE TITLE
UI fixes in book suggestion modal.

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/employee-portal#480]
![image](https://user-images.githubusercontent.com/10670690/41521738-f8160cc4-72f0-11e8-879c-4084cb5f15f6.png)
-

**Comment by rathorevaibhav** [comment]
@pankaj-ag is this fixed? If yes, I think we should close this issue otherwise we can target this in upcoming milestones.

**Comment by abhishek-pokhriyal** [comment]
Closing this one as complete. Please reopen if you found any issues in this area.
