### ISSUE TITLE
Update books page 

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/employee-portal#482]
![image](https://user-images.githubusercontent.com/10670690/41523733-adcd0606-72f8-11e8-8f5b-bf474e1463b3.png)

Fix the alignment in all the devices.

**Comment by abhishek-pokhriyal** [comment]
After discussing with @pankaj-ag what I understood about this issue.
The layout of the page that displays all the books breaks when the device is width is between `768px` to `991px`, that is, tablet screen. 

The layout renders fine for all the other screen sizes.

**Comment by rathorevaibhav** [comment]
This is complete. Closing.
