### ISSUE TITLE
Mandatory Field sign is missing

### ISSUE THREAD

**Issue by PrateekNarang** [ColoredCow/employee-portal#49]
I can't tell on Project creation screen which fields are mandatory. Please check throughout the site and give a clear indication which fields are mandatory.

**Comment by rathorevaibhav** [comment]
Added validations. Screenshot below
![image](https://user-images.githubusercontent.com/12053186/38425599-f6288b38-39d1-11e8-824e-4b8e933d4299.png)

Similar boxes will show up on Client and Project's create and edit screens as well when server-side validations fail.

**Comment by rathorevaibhav** [comment]
Error reporting complete. Closing.
