### ISSUE TITLE
Client ID field is missing

### ISSUE THREAD

**Issue by PrateekNarang** [ColoredCow/employee-portal#50]
There should be a field for Client ID at the time of creation of client.
We follow 019-001-000004
Where 019 is Client ID
001 is the project ID
000004 is the invoice number.
At every step, we should capture this information.

**Comment by rathorevaibhav** [comment]
Client ID is autogenerated using the default SQL indexing. For clarification, the best thing would be to show this ID. Can be tracked separately. Closing.
