### ISSUE TITLE
Set max width for book cards. 

### ISSUE THREAD

**Issue by pankaj-ag** [ColoredCow/employee-portal#516]
![image](https://user-images.githubusercontent.com/10670690/41807189-764b769c-76e8-11e8-8ad1-889c8bcfb48c.png)

![image](https://user-images.githubusercontent.com/10670690/41807193-8220e628-76e8-11e8-9e54-99bb9e185cee.png)

If there are less then 4 items in the row then items trying to take the full width of that row. Can we fix that by setting up max width or something else?

**Comment by abhishek-pokhriyal** [comment]
@pankaj-ag I think this is solved. Could you check and give an update?

**Comment by pankaj-ag** [comment]
Can you reference the PR or issue here?

**Comment by abhishek-pokhriyal** [comment]
@pankaj-ag I am not able to see the issue you mentioned when I open the book page. Here are the screenshots:
![screenshot 96](https://user-images.githubusercontent.com/11808845/42723265-692dfd22-8778-11e8-99e0-62937d47ea73.png)
![screenshot 97](https://user-images.githubusercontent.com/11808845/42723266-6e1a329c-8778-11e8-90fc-8c85b96a1859.png)

**Comment by abhishek-pokhriyal** [comment]
This is complete. Closing this.
