### ISSUE TITLE
More details on Project

### ISSUE THREAD

**Issue by PrateekNarang** [ColoredCow/employee-portal#52]
<img width="829" alt="screen shot 2018-04-04 at 6 16 51 pm" src="https://user-images.githubusercontent.com/772597/38308357-74ca1622-3834-11e8-9a68-9878f409d5ca.png">

1. There are two kinds of projects
    a. Fixed Budget
    b. Hourly
Details should be captured at the project creation
2. Taxes details should be captured. GST can be included in the fixed budget or it can be excluded. 
3. Client can deduct TDS. This information should be captured at the time of receiving.
4. For fixed budget, the payment can be divided into parts. For example 30-30-40. At the time of the contract, the dates are decided. This means that multiple invoices can be part of one project.
5. On project detail all this information should appear. 
See the attached image.

**Comment by rathorevaibhav** [comment]
@PrateekNarang my comments below:

1. We can add a project type field (select field) in the project dashboard. Is there a change that we can edit project type from fixed budget to hourly? If that's the case, we may have to store more meta for the invoice (like if the invoice was fixed budget or hourly type).
2. GST field understood. This will be an amount field. GST will be added at the time of sending an invoice. I believe GST won't be applicable to hourly project right?
3. TDS field understood. This will be an amount field. TDS will be added at the time of receiving payment.
4. Division of payment understood.

Let me work on a workflow and will share once done.

**Comment by rathorevaibhav** [comment]
From our discussion:

1. Project type can be edited from the Project edit screen.
2. GST field would be a field Project create/edit.
3. Since TDS can vary from invoice to invoice, it needs to be shown on the invoice screen.
4. Division of payment should be done at the time of project creation. Can be editable. Moreover, right now invoice is attached to project(s), we can also attach an invoice to the invoice breakup id.

**Comment by rathorevaibhav** [comment]
Based on our discussion, this one needs a bit more structure and corresponding workflow.

1. Project cost can be changed later. This can impact the invoice breakups for that project as their summation cost won't be same as the total project cost.
2. An invoice can also be generated without any selection of invoice breakup for that project. It can represent a separate invoice.

Suggestions:

1. We can use versioning of a project. For example, to add a cost, a new project version is created.
2. Each version can have a name, breakup and invoices attached to that breakup.
3. In case an invoice is generated without selecting any project version breakup, it can be shown as a separate project version without any breakup.
4. From the invoice screen, a project can be selected and the next should be it's version. After version is selected, we can show a list of breakup for that version for which the invoice is generated.

**Comment by rathorevaibhav** [comment]
Test and UI/UX feedback are being tracked in #116 and #115 respectively
