### ISSUE TITLE
Extra white space in after apply  any functionality into   module  

### ISSUE THREAD

**Issue by mohitgusain** [ColoredCow/employee-portal#609]
**Initially Screen looks like**
![screenshot 28](https://user-images.githubusercontent.com/30264862/43142015-058972b0-8f75-11e8-8db9-a195183ba70d.png)

**After applied any functionality**
![screenshot 29](https://user-images.githubusercontent.com/30264862/43142102-40d95f56-8f75-11e8-8293-c854473903bd.png)

as we see in the second screen there is extra white space after **Edit Client** as a comparison to the above screen.
Also check it into another module once.

**Comment by abhishek-pokhriyal** [comment]
@rathorevaibhav can we close this?
