### ISSUE TITLE
Able to create empty project billing

### ISSUE THREAD

**Issue by rathorevaibhav** [ColoredCow/employee-portal#621]
![image](https://user-images.githubusercontent.com/12053186/43249021-33807386-90d7-11e8-8566-b1903cabdef4.png)

**Comment by Satendra-SR** [comment]
@rathorevaibhav 
I think we have an issue #594 similar to this. please check and confirm.

**Comment by rathorevaibhav** [comment]
Agreed. This is a duplicate of #594. Closing here.
