### ISSUE TITLE
Payment Type needs to be added

### ISSUE THREAD

**Issue by PrateekNarang** [ColoredCow/employee-portal#68]
In received amount, I should have an option to mention the type of mod we received the money, like by cheque, cash, or wire transfer. We can wait for BitCoins :-)

**Comment by rathorevaibhav** [comment]
@PrateekNarang I've added the following three payment types with their display names:

```
1. cheque => Cheque
2. cash => Cash
3. wire-transfer => Wire Transfer
```

Can you confirm if these are fine? Any additions/modifications you want to suggest?

**Comment by rathorevaibhav** [comment]
@PrateekNarang this is ready for testing. Have a look.

**Comment by rathorevaibhav** [comment]
This is complete. Closing.
