### ISSUE TITLE
In-active state should be automatic

### ISSUE THREAD

**Issue by PrateekNarang** [ColoredCow/employee-portal#74]
In-Active state for a client should be automatic. Otherwise, there is a lot of clutter in the drop-down. Something like if we have not sent them an invoice for more than three months, they should be qualified for inactive state.

**Comment by rathorevaibhav** [comment]
@PrateekNarang I think for the initial version, we can add a flag to the client edit screen to set the state for the client. Basically "active" or "inactive". On the projects and invoices screens, we can then only show the clients with the state set to active.

**Comment by PrateekNarang** [comment]
Agree.
